name: (CI)

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.FSC-PS/**'
      - 'tests/**'
    branches:
       - main
   
permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
   CI:
    runs-on: [ windows-latest ]
    name: Gated Build
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Initialize the workflow
        uses: fscpscollaborative/fscps.gh/WorkflowInitialize@v2.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: fscpscollaborative/fscps.gh/ReadSettings@v2.1

      - name: Read secrets
        uses: fscpscollaborative/fscps.gh/ReadSecrets@v2.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}

      - name: Check for updates to FSC-PS system files
        uses: fscpscollaborative/fscps.gh/CheckForUpdates@v2.1
        continue-on-error: true
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2.0.0
        with:
          nuget-version: 5.10.x    
          
      - name: Run pipeline
        uses: fscpscollaborative/fscps.gh/RunPipeline@v2.1
        id: runpipeline
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          
      - name: Add logs to job summary
        run: |
          $logFiles = Get-ChildItem -Path "${{ env.ARTIFACTS_PATH }}\Logs" -Recurse -Filter *.log
          $summary = "# Logs `n`n"
          if ($logFiles) {
              foreach ($logFile in $logFiles) {
                  $content = Get-Content -Path $logFile
                  $summary += "## $logFile `n"
                  foreach ($line in $content) {
                      # if the line consists only of = or - characters 
                      # (which would be interpreted as a setext heading 
                      # (https://github.github.com/gfm/#setext-headings)), 
                      # add a new line before it
                      if ($line -match "^[=-]+$") {
                          $summary += "`n$line`n"
                      } else {
                        $summary += $line + "`n"
                      } 
                  }
              }
          }
          $summary >> $env:GITHUB_STEP_SUMMARY
                     
      - name: Finalize the workflow
        id: PostProcess
        uses: fscpscollaborative/fscps.gh/WorkflowPostProcess@v2.1
        with:
          remove_current: ${{ steps.ReadSettings.outputs.EnvironmentsJson == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}