name: (CI)

on:
  workflow_dispatch:
  pull_request:
     branches:
       - main
   
permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
   Initialization:
    runs-on: [ windows ]
    outputs:
      settings: ${{ steps.ReadSettings.outputs.SettingsJson }}
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Check for updates to FSC-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.1
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}

   Build:
    needs: [ Initialization ]
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    strategy:
      matrix:
        version: ${{ fromJson(needs.Initialization.outputs.versions) }}
      fail-fast: false
    name: Gated Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
        with:
          version: ${{ matrix.version }}

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.0.7
        with:
          nuget-version: 5.10.x    
          
      - name: Run pipeline
        uses: ciellosinc/FSC-PS-Actions/RunPipeline@v1.1
        id: runpipeline
        with:
          type: ${{ needs.Initialization.outputs.type}}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          
   PostProcess: 
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}