name: (CI)

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.FSC-PS/**'
      - 'tests/**'
    branches:
       - main
   
permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
   CI:
    runs-on: [ windows-latest ]
    name: Gated Build
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}

      - name: Check for updates to FSC-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.1
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.0.7
        with:
          nuget-version: 5.10.x    
          
      - name: Run pipeline
        uses: ciellosinc/FSC-PS-Actions/RunPipeline@v1.1
        id: runpipeline
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
                   
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ steps.ReadSettings.outputs.EnvironmentsJson == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}