name: (DEPLOY)

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Select FSCM Environment'
        required: false
        default: ''
        type: choice
        options:
        - "*"

permissions:
  contents: read

defaults:
  run:
    shell: PowerShell

jobs:
   Initialization:
    runs-on: [ windows-latest ]
    outputs:
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
        with:
          environment: ${{ inputs.environment }}

      - name: Check for updates to FSC-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.1
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}
   Deploy:
    needs: [ Initialization ]
    if: needs.Initialization.outputs.environments != ''
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ fromJson(needs.Initialization.outputs.environments) }}
      fail-fast: false
    name: Deploy ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         ref: ${{ needs.Initialization.outputs.source_branch }}
         
      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
        with:
          environment: ${{ matrix.environment }}
          
      - name: Checkout ${{ steps.ReadSettings.outputs.SOURCE_BRANCH }}
        if: steps.ReadSettings.outputs.SOURCE_BRANCH != needs.Initialization.outputs.source_branch
        uses: actions/checkout@v3
        with:
         ref: ${{ steps.ReadSettings.outputs.SOURCE_BRANCH }}
         
      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.0.7
        with:
          nuget-version: 5.10.x    
          
      - name: Run pipeline
        uses: ciellosinc/FSC-PS-Actions/RunPipeline@v1.1
        id: runpipeline
        with:
          type: ${{ needs.Initialization.outputs.type}}
          environment_name: ${{ matrix.environment }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
      
      - name: Publish artifacts  
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.ARTIFACTS_PATH }}
          
   PostProcess: 
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Deploy ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
