name: (IMPORT)

on:
  workflow_dispatch:
   inputs:
     archiveUrl:
        description: Direct download URL to the sources archive
        required: false
        default: ''
permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
   Initialization:
    runs-on: [ windows-latest ]
    outputs:
      settings: ${{ steps.ReadSettings.outputs.SettingsJson }}
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    
        

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

   Build:
    needs: [ Initialization ]
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    name: Import sources
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
   
      - name: Import sources
        uses: ciellosinc/FSC-PS-Actions/Import@v1.1
        with:
          type: ${{ needs.Initialization.outputs.type}}
          artifactsPath: ${{ github.event.inputs.archiveUrl }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          
   PostProcess: 
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Build ]
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}