name: (UPDATE) FSC-PS System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (only if a change is needed)
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
        
permissions:
  contents: read

defaults:
  run:
    shell: pwsh
    
env:
  FORCE_COLOR: 3

jobs:
   Initialization:
    runs-on: [ windows-latest ]
    outputs:
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:

      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

   Update:
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
        
      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Override TemplateUrl
        run: |
          $templateUrl = '${{ github.event.inputs.templateUrl }}'
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateUrl=$templateUrl"
          }

      - name: Calculate DirectCommit
        env:
          directCommit: ${{ github.event.inputs.directCommit }}
          eventName: ${{ github.event_name }}
        run: |
          $directCommit = $ENV:directCommit
          Write-Host $ENV:eventName
          if ($ENV:eventName -eq 'schedule') {
            Write-Host "Running Update System Files on a schedule. Setting DirectCommit = Y"
            $directCommit = 'Y'
          }
          Add-Content -Path $env:GITHUB_ENV -Value "DirectCommit=$directCommit"

      - name: Check for updates to FSCM-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.1
        with:
          type: ${{ needs.Initialization.outputs.type}}
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          update: Y
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          templateUrl: ${{ env.TemplateUrl }}
          directCommit: ${{ env.directCommit }}
          
   PostProcess: 
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Update ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}