name: (UPDATE_ISV)

on:
  workflow_dispatch:
   inputs:
     archiveUrl:
        description: Direct download URL to the sources archive
        required: false
        default: ''
        
permissions:
  pull-requests: write
  issues: write
  contents: write
  repository-projects: write

defaults:
  run:
    shell: pwsh

jobs:
   Initialization:
    runs-on: [ windows-latest ]
    outputs:
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.2
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    
        

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.2

   Build:
    needs: [ Initialization ]
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    name: Update sources
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          
      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.2
   
      - name: Update models
        uses: ciellosinc/FSC-PS-Actions/UpdateISVModels@v1.2
        with:
          type: ${{ needs.Initialization.outputs.type}}
          artifactsPath: ${{ github.event.inputs.archiveUrl }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          
   PostProcess: 
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Build ]
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.2

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.2
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.2
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}